### PR TITLE
Basic webpage

### PR DESCRIPTION
**Pull request by chris-allnutt**
Basic Webpage for landing.

@andreagoulet

### CODE REVIEW

**Comment by andreagoulet** [comment]
I think this is ready to go but it needs a favicon and we need to figure out hosting. @mscottford suggested Amazon S3.

**Comment by mscottford** [comment]
I vote that we use GitHub's project page support to host this. https://help.github.com/articles/user-organization-and-project-pages/

**Comment by mscottford** [comment]
Also this page has other setup information. https://help.github.com/articles/configuring-a-publishing-source-for-github-pages/

**Comment by chris-allnutt** [comment]
@andreagoulet @mscottford has been rebased with master and I added a favicon.  I'll look into the page publishing next but would like to get this merged before I proceed.

**Comment by chris-allnutt** [comment]
@andreagoulet @mscottford I've moved the content to the docs directory so it will work with github pages.  However I do not have the requisite permissions to change the Settings on the repository so that's something one of you will have to do.

**Pull request merged**
