### PR TITLE
Move js files to subdir and bring android up to speed 

### PR DESCRIPTION
**Pull request by gitanshu**

### CODE REVIEW

**Comment by andreagoulet** [comment]
@mscottford @chris-allnutt or @tonygambone could one of you please review and provide feedback for merging?

**Comment by chris-allnutt** [comment]
@andreagoulet @gitanshu LGTM.  This basically makes both apps use the same root page which will make dev easier. :shipit:

**Comment by gitanshu** [comment]
Yup. If we need subtle platform specific changes, one can use the Platform API available in RN. For bigger changes, we can make platform specific file (<name>.android.js and <name>.ios.js).

**Comment by andreagoulet** [comment]
Awesome. I'll go ahead and merge it. :)

**Pull request merged**
