### PR TITLE
App structure for server side

### PR DESCRIPTION
**Pull request by tonygambone**
This is the result of doing `feathers generate` and setting up some defaults. I also added a 'scripts' service to feathers and set up docker-compose for running the app and MongoDB.  Not sure if it's totally working yet, but ideally you just run `docker-compose up` and there you go.

### CODE REVIEW

**Comment by chris-allnutt** [comment]
@mscottford per my comments on #20 @tonygambone is using the server sub dir.  We should probably establish how we want to handle this.

**Comment by chris-allnutt** [comment]
@andreagoulet @mscottford we need at least one other person to confirm this is working.  Would prefer it to be one of you two.  Otherwise I'd say lets get it in and get rocking on this.

**Comment by tonygambone** [comment]
I'd also like someone else to confirm it works!

As far as organization, we could combine the server side components (essentially the web/ and server/ directories) into one app - serve the website mostly as static files and also host the API.  We'll probably also need a basic admin interface behind authentication.

If there's interest in working on the site without docker or mongodb, or using a local mongodb instead of the dockerized one, that'll probably take more work - I don't think the feathers app will start up unless it can talk to mongodb.

**Comment by tonygambone** [comment]
Alternatively, we could keep website and API/admin interface as distinct projects, and host the API under a subdomain.

**Comment by chris-allnutt** [comment]
@tonygambone I like to think of things as individually build able components.  I don't think mixing the static site with the API makes sense.  they can live on the same physical server but they're not directly tied to each other.  I'm usually partial to keeping things as distinct projects, but I can understand the desire for simplicity of a single repo.

**Comment by tonygambone** [comment]
@chris-allnutt Sounds good to me. I'd also be fine splitting the repos as you suggested in #20; I would normally do it that way too (one repo = one output).

**Review by mscottford — APPROVED** [review]
I like it! Thanks, @tonygambone.

**Comment by mscottford** [comment]
I pulled it down and got it running and confirmed that it's working. I left that detail out of my earlier comment. :)

**Comment by chris-allnutt** [comment]
:shipit: @tonygambone do you have Merge privileges, or do you need myself @mscottford or @andreagoulet to merge it for you?

**Comment by tonygambone** [comment]
I don't have privs here, no.

**Comment by andreagoulet** [comment]
You do now @tonygambone :)

**Comment by chris-allnutt** [comment]
@tonygambone merged.

**Comment by tonygambone** [comment]
TYVM 👍

**Pull request merged**
